<?php $title = 'Remediation Tasks'; ?>
<div class="container-fluid py-4">
    <div class="d-flex justify-content-between align-items-end gap-3 mb-4">
        <div><h1 class="h3 mb-1">Remediation Tasks</h1><div class="text-muted">Manage privacy remediation tasks by client.</div></div>
        <?php if ($client): ?><a class="btn btn-primary" href="<?= url('tasks/create',['client_id'=>(int)$client['id']]) ?>">New task</a><?php endif; ?>
    </div>
    <?php if ($clients): ?>
    <div class="card mb-4"><div class="card-header"><strong>Select client</strong><div class="small text-muted">Choose the organisation whose remediation tasks you want to view.</div></div><div class="card-body"><select class="form-select" id="tasks-client" aria-label="Select client"><option value="">Select a client...</option><?php foreach ($clients as $item): ?><option value="<?= (int)$item['id'] ?>" <?= $client && (int)$client['id']===(int)$item['id']?'selected':'' ?>><?= e($item['company_name']) ?></option><?php endforeach; ?></select></div></div>
    <?php endif; ?>
    <?php if ($client): ?>
    <div class="card border-0 shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><strong>Remediation Tasks for <?= e($client['company_name']) ?></strong><span class="badge bg-secondary"><?= count($tasks) ?> <?= count($tasks)===1?'task':'tasks' ?></span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Task</th><th>Priority</th><th>Status</th><th>Assignee</th><th>Due</th><th></th></tr></thead><tbody><?php foreach($tasks as $task): ?><tr><td><div class="fw-semibold"><?= e($task['title']) ?></div><?php if(!empty($task['description'])):?><small class="text-muted"><?= e($task['description']) ?></small><?php endif;?></td><td><?= e(ucfirst($task['priority'])) ?></td><td><?= e(ucwords(str_replace('_',' ',$task['status']))) ?></td><td><?= e($task['assignee_name']??'Unassigned') ?></td><td><?= e($task['due_date']??'—') ?></td><td><form method="post" action="<?= url('tasks/status',['client_id'=>(int)$client['id']]) ?>" class="d-flex gap-1"><?php include __DIR__.'/../partials/csrf.php'; ?><input type="hidden" name="id" value="<?= (int)$task['id'] ?>"><select name="status" class="form-select form-select-sm"><option value="open">Open</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button class="btn btn-sm btn-outline-primary">Update</button></form></td></tr><?php endforeach; ?><?php if(!$tasks): ?><tr><td colspan="6" class="text-center text-muted py-5">No remediation tasks yet.</td></tr><?php endif; ?></tbody></table></div></div>
    <?php endif; ?>
</div>
<?php if($clients): ?><script>document.getElementById('tasks-client')?.addEventListener('change',function(){if(!this.value)return;const u=new URL(window.location.href);u.searchParams.set('route','tasks');u.searchParams.set('client_id',this.value);window.location.href=u.toString();});</script><?php endif; ?>
