<?php
$template = $template ?? [];
$version = $version ?? [];
$definition = $version['definition'] ?? ['sections'=>[]];
?>
<div class="page-header d-flex justify-content-between align-items-center mb-4"><div><div class="page-title"><?= e($template['name']) ?></div><div class="page-subtitle mb-0">Create a new immutable version. Current version: v<?= (int)($version['version_number'] ?? 0) ?></div></div><a class="btn btn-outline-secondary" href="<?= url('forms/templates/'.$template['slug'].'/versions') ?>">Version history</a></div>
<form method="post" action="<?= url('forms/templates/store') ?>" id="templateEditor">
<input type="hidden" name="_csrf" value="<?= e(Security::csrfToken()) ?>"><input type="hidden" name="slug" value="<?= e($template['slug']) ?>"><input type="hidden" name="definition" id="definition">
<div id="sections"></div>
<div class="mt-3"><button type="button" class="btn btn-outline-primary" id="addSection">+ Add section</button></div>
<div class="card mt-4"><div class="card-body"><label class="form-label">Change summary</label><input class="form-control" name="change_summary" placeholder="Describe what changed in this version"><div class="mt-3 d-flex justify-content-end"><button class="btn btn-primary">Create new version</button></div></div></div>
</form>
<script>
const state=<?= json_encode($definition,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;const root=document.getElementById('sections');
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function render(){root.innerHTML='';(state.sections||[]).forEach((sec,si)=>{const box=document.createElement('div');box.className='card mb-4';box.innerHTML=`<div class="card-body"><div class="d-flex gap-2 mb-3"><input class="form-control" value="${esc(sec.title)}" placeholder="Section title" data-sec-title="${si}"><button type="button" class="btn btn-outline-danger" data-del-sec="${si}">Delete</button></div><input class="form-control mb-3" value="${esc(sec.description||'')}" placeholder="Section description" data-sec-desc="${si}"><div data-fields="${si}"></div><button type="button" class="btn btn-sm btn-outline-primary" data-add-field="${si}">+ Add field</button></div>`;root.appendChild(box);const fields=box.querySelector('[data-fields]');(sec.fields||[]).forEach((f,fi)=>{const row=document.createElement('div');row.className='border rounded p-3 mb-2';row.innerHTML=`<div class="row g-2"><div class="col-md-3"><input class="form-control" value="${esc(f.key)}" placeholder="Field key"></div><div class="col-md-3"><input class="form-control" value="${esc(f.label)}" placeholder="Label"></div><div class="col-md-2"><select class="form-select"><option ${f.type==='text'?'selected':''}>text</option><option ${f.type==='textarea'?'selected':''}>textarea</option><option ${f.type==='select'?'selected':''}>select</option><option ${f.type==='multiselect'?'selected':''}>multiselect</option><option ${f.type==='client'?'selected':''}>client</option></select></div><div class="col-md-2"><input class="form-control" value="${esc((f.options||[]).join(', '))}" placeholder="Options, comma separated"></div><div class="col-md-1 form-check pt-2"><input class="form-check-input" type="checkbox" ${f.required?'checked':''}><label class="form-check-label">Required</label></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger" data-del-field="${si}:${fi}">×</button></div></div>`;fields.appendChild(row);row.querySelectorAll('input,select').forEach((el,idx)=>el.addEventListener('input',()=>{f.key=row.querySelectorAll('input')[0].value.trim();f.label=row.querySelectorAll('input')[1].value;f.type=row.querySelector('select').value;f.options=row.querySelectorAll('input')[2].value.split(',').map(x=>x.trim()).filter(Boolean);f.required=row.querySelector('input[type=checkbox]').checked;}));});});}
root.addEventListener('click',e=>{const t=e.target;if(t.dataset.delSec!==undefined){state.sections.splice(+t.dataset.delSec,1);render();}if(t.dataset.addField!==undefined){state.sections[+t.dataset.addField].fields??=[];state.sections[+t.dataset.addField].fields.push({key:'new_field',label:'New field',type:'text',required:false});render();}if(t.dataset.delField!==undefined){const [s,f]=t.dataset.delField.split(':').map(Number);state.sections[s].fields.splice(f,1);render();}});document.getElementById('addSection').onclick=()=>{state.sections??=[];state.sections.push({title:'New section',description:'',fields:[]});render();};document.querySelectorAll('[data-sec-title]').forEach(()=>{});render();document.getElementById('templateEditor').onsubmit=()=>{state.sections.forEach((s,si)=>{const box=root.children[si];s.title=box.querySelector('[data-sec-title]')?.value||s.title;s.description=box.querySelector('[data-sec-desc]')?.value||'';});document.getElementById('definition').value=JSON.stringify(state);};
</script>
