<?php
namespace App\Controllers;
use App\Core\BaseController;
use App\Core\Security;
use App\Models\Client;
use App\Models\Ropa;

class FormsController extends BaseController
{
 private function forms():array{return [['name'=>'Data Subject Access Request','description'=>'Capture and manage requests from data subjects to access their personal data.','category'=>'Data Subject Rights','status'=>'Available'],['name'=>'Consent Record','description'=>'Record consent collection, purpose, source and withdrawal information.','category'=>'Consent Management','status'=>'Available'],['name'=>'Privacy Incident Report','description'=>'Capture the initial details of a suspected privacy or personal-data incident.','category'=>'Incident Management','status'=>'Available'],['name'=>'Data Processing Review','description'=>'Structured review form for documenting a processing activity and its privacy controls.','category'=>'Processing Activities','status'=>'Available'],['name'=>'Record of Processing Activities','description'=>'Create and maintain a complete ROPA record for each processing activity.','category'=>'Processing Activities','status'=>'Available'],['name'=>'Privacy Risk Assessment','description'=>'Collect information required to assess privacy risks associated with a project or process.','category'=>'Assessments','status'=>'Available'],['name'=>'Vendor Privacy Questionnaire','description'=>'Gather privacy and data-protection information from third-party vendors.','category'=>'Third Parties','status'=>'Available']];}
 private function canSelectClient():bool{$role=strtolower((string)($_SESSION['user']['role']??''));return in_array($role,['superuser','admin'],true);}
 private function resolveClient():?array{$id=(int)($_GET['client_id']??$_POST['client_id']??0);if($id<=0&&$this->clientId())$id=$this->clientId();if($id<=0&&$this->canSelectClient()){ $clients=(new Client())->allClients();$id=(int)($clients[0]['id']??0); }if($id<=0)return null;$client=(new Client())->find($id);if(!$client)return null;$this->requireClientAccess((int)$client['id']);return $client;}
 public function index():void{$this->requireLogin();$this->view('forms/index',['title'=>'Forms','forms'=>$this->forms()]);}
 public function riskAssessment():void{$this->requireLogin();$model=new Client();if($this->clientId()){$client=$model->find($this->clientId());$clients=$client?[$client]:[];}else{$clients=$model->allClients();}$this->view('forms/privacy-risk-assessment',['title'=>'Privacy Risk Assessment','clients'=>$clients]);}
 public function ropa():void{$this->requireLogin();$client=$this->resolveClient();if(!$client){if(!$this->canSelectClient()&&!$this->clientId()){http_response_code(403);exit('No client is assigned to this account');}redirect('forms');return;}$clients=$this->canSelectClient()?(new Client())->allClients():[$client];$records=(new Ropa())->forClient((int)$client['id']);$id=(int)($_GET['id']??0);$ropa=[];$record=null;if($id>0){$record=(new Ropa())->find($id);if(!$record||(int)$record['client_id']!==(int)$client['id']){http_response_code(404);exit('ROPA record not found');}$ropa=$record['data'];$ropa['id']=$record['id'];$ropa['client_id']=$record['client_id'];$ropa['process_name']=$record['process_name'];$ropa['status']=$record['status'];$_SESSION['ropa_edit_id']=$record['id'];}else{unset($_SESSION['ropa_edit_id']);}$this->view('forms/ropa',compact('client','clients','records','record','ropa'));}
 public function ropaStore():void{$this->requireLogin();if(!Security::verifyCsrf($_POST['_csrf']??null)){http_response_code(419);exit('Invalid security token');}$client=$this->resolveClient();if(!$client){http_response_code(403);exit('Organisation access denied');}$processName=trim((string)($_POST['process_name']??''));if($processName===''){http_response_code(422);exit('Processing activity / process is required');}$payload=$_POST;unset($payload['_csrf']);$payload['client_id']=(int)$client['id'];$data=['client_id'=>(int)$client['id'],'process_name'=>$processName,'status'=>trim((string)($_POST['status']??'planned')),'payload'=>$payload,'created_by'=>(int)($_SESSION['user']['id']??0)];$model=new Ropa();$id=(int)($_POST['id']??($_SESSION['ropa_edit_id']??0));if($id>0){$data['id']=$id;$record=$model->find($id);if(!$record||(int)$record['client_id']!==(int)$client['id']){http_response_code(404);exit('ROPA record not found');}$model->update($data);}else{$id=$model->create($data);}$_SESSION['ropa_edit_id']=$id;redirect('forms/ropa?client_id='.$client['id'].'&id='.$id);}
}
