<?php
namespace App\Controllers;
use App\Core\BaseController;
use App\Core\Security;
use App\Models\AdminClientAccess;
use App\Models\Client;
use App\Models\FormTemplate;
use App\Models\Ropa;

class FormsController extends BaseController
{
 private function forms():array{return [['name'=>'Data Subject Access Request','description'=>'Capture and manage requests from data subjects to access their personal data.','category'=>'Data Subject Rights','status'=>'Coming Soon'],['name'=>'Consent Record','description'=>'Record consent collection, purpose, source and withdrawal information.','category'=>'Consent Management','status'=>'Coming Soon'],['name'=>'Privacy Incident Report','description'=>'Capture the initial details of a suspected privacy or personal-data incident.','category'=>'Incident Management','status'=>'Coming Soon'],['name'=>'Data Processing Review','description'=>'Structured review form for documenting a processing activity and its privacy controls.','category'=>'Processing Activities','status'=>'Coming Soon'],['name'=>'Record of Processing Activities','description'=>'Create and maintain a complete ROPA record for each processing activity.','category'=>'Processing Activities','status'=>'Available'],['name'=>'Privacy Risk Assessment','description'=>'Structured review form for documenting privacy risks associated with a project or process.','category'=>'Assessments','status'=>'Coming Soon'],['name'=>'Vendor Privacy Questionnaire','description'=>'Gather privacy and data-protection information from third-party vendors.','category'=>'Third Parties','status'=>'Coming Soon']];}
 private function canSelectClient():bool{return $this->isSuperuser()||$this->isAdmin();}
 protected function isSuperuser():bool{return $this->role()==='superuser'||(int)($this->user()['role_id']??0)===1;}
 private function assignedClients():array
 {
  if($this->isSuperuser()) return (new Client())->allClients();
  if($this->isAdmin()) return (new AdminClientAccess())->clientsForAdmin((int)($this->user()['id']??0));
  if($this->isClientUser()){ $client=$this->clientId(); if(!$client)return []; $row=(new Client())->find($client); return $row?[$row]:[]; }
  return [];
 }
 private function canAccessFormClient(int $clientId):bool
 {
  if($this->isSuperuser()) return true;
  if($this->isClientUser()) return $this->clientId()===$clientId;
  if($this->isAdmin()) return (new AdminClientAccess())->canAccess((int)($this->user()['id']??0),$clientId);
  return false;
 }
 private function resolveClient():?array
 {
  $id=(int)($_GET['client_id']??$_POST['client_id']??0);
  if($id<=0&&$this->clientId())$id=$this->clientId();
  if($id<=0){$clients=$this->assignedClients();$id=(int)($clients[0]['id']??0);}
  if($id<=0){http_response_code(404);$this->view('errors/403',['title'=>'No organisation available','message'=>'Create or assign an organisation before opening this form.']);exit;}
  if(!$this->canAccessFormClient($id)){http_response_code(403);$this->view('errors/403',['title'=>'Access denied','message'=>'You do not have access to this client or its form data.']);exit;}
  $client=(new Client())->find($id); if(!$client){http_response_code(404);exit('Client not found');} return $client;
 }
 private function ropaSlug(string $role):string{return strtolower($role)==='processor' ? 'ropa-processor' : 'ropa-controller';}
 private function definitionFields(array $definition,string $role):array
 {
  $fields=[]; foreach(($definition['sections']??[]) as $section){foreach(($section['fields']??[]) as $field){$roles=array_values(array_filter((array)($field['roles']??[])));if(!$roles||in_array($role,$roles,true))$fields[(string)($field['key']??'')]=$field;}} return array_filter($fields,static fn($key)=>$key!=='',ARRAY_FILTER_USE_KEY);
 }
 private function fieldVisible(array $field,array $input):bool
 {
  if(empty($field['show_when'])||!is_array($field['show_when']))return true;$source=(string)($field['show_when']['field']??'');$equals=(string)($field['show_when']['equals']??'');$actual=$input[$source]??null;if(is_array($actual))return in_array($equals,array_map('strval',$actual),true);return (string)$actual===$equals;
 }
 private function validateRopaPayload(array $definition,array $input,string $role,int $clientId):array
 {
  $fields=$this->definitionFields($definition,$role);$payload=['client_id'=>$clientId,'ropa_role'=>$role];$errors=[];foreach($fields as $key=>$field){$type=(string)($field['type']??'text');if($key==='client_id')continue;if(in_array($type,['auto','auto_date','verification','derived_date'],true)){if($type==='auto_date')$payload[$key]=date('Y-m-d');elseif($type==='derived_date'){$source=(string)($field['derived_from']??'');$base=trim((string)($input[$source]??''));$derived='';if($base!==''){try{$d=\DateTime::createFromFormat('Y-m-d',$base);if($d&&$d->format('Y-m-d')===$base){$d->modify('+' . (int)($field['offset_months']??0) . ' months');$derived=$d->format('Y-m-d');}}catch(\Throwable $e){}}$payload[$key]=$derived;}else{$payload[$key]=trim((string)($input[$key]??''));}continue;}if(!$this->fieldVisible($field,$input)){$payload[$key]=($type==='multiselect'?[]:'');continue;}$value=$input[$key]??null;if($type==='multiselect'){$values=is_array($value)?$value:($value===null||$value===''?[]:[(string)$value]);$values=array_values(array_unique(array_map('strval',$values)));$options=array_map('strval',(array)($field['options']??[]));if($options)$values=array_values(array_intersect($values,$options));if(!empty($field['required'])&&!$values)$errors[]=(string)($field['label']??$key).' requires at least one selection.';$payload[$key]=$values;continue;}$value=is_array($value)?'':trim((string)($value??''));if(!empty($field['required'])&&$value==='')$errors[]=(string)($field['label']??$key).' is required.';if($type==='select'&&$value!==''&&!empty($field['options'])&&!in_array($value,array_map('strval',$field['options']),true))$errors[]=(string)($field['label']??$key).' contains an invalid option.';if($type==='date'&&$value!==''){$d=\DateTime::createFromFormat('Y-m-d',$value);if(!$d||$d->format('Y-m-d')!==$value)$errors[]=(string)($field['label']??$key).' must be a valid date.';}$payload[$key]=$value;}if($errors){http_response_code(422);exit(implode("\n",$errors));}return $payload;
 }
 public function index():void{$this->requireLogin();$this->view('forms/index',['title'=>'Forms','forms'=>$this->forms(),'canManage'=>$this->isSuperuser()]);}
 public function manage():void{$this->requireLogin();if(!$this->isSuperuser()){http_response_code(403);exit('Superuser access required');}$templates=(new FormTemplate())->all();$this->view('forms/manage',['title'=>'Manage Form Templates','templates'=>$templates]);}
 public function templateEdit():void{$this->requireLogin();if(!$this->isSuperuser()){http_response_code(403);exit('Superuser access required');}$slug=trim((string)($_GET['slug']??''));$template=(new FormTemplate())->findBySlug($slug);if(!$template){http_response_code(404);exit('Form template not found');}$active=(new FormTemplate())->active($slug);$this->view('forms/template-editor',['title'=>'Edit '.$template['name'].' template','template'=>$template,'version'=>$active]);}
 public function templateVersions():void{$this->requireLogin();if(!$this->isSuperuser()){http_response_code(403);exit('Superuser access required');}$slug=trim((string)($_GET['slug']??''));$template=(new FormTemplate())->findBySlug($slug);if(!$template){http_response_code(404);exit('Form template not found');}$versions=(new FormTemplate())->versions($slug);$this->view('forms/template-versions',['title'=>$template['name'].' version history','template'=>$template,'versions'=>$versions]);}
 public function templateStore():void{$this->requireLogin();if(!$this->isSuperuser()){http_response_code(403);exit('Superuser access required');}if(!Security::verifyCsrf($_POST['_csrf']??null)){http_response_code(419);exit('Invalid security token');}$slug=trim((string)($_POST['slug']??''));$definition=json_decode((string)($_POST['definition']??''),true);$summary=trim((string)($_POST['change_summary']??''));if(!$slug||!is_array($definition)){http_response_code(422);exit('Invalid form definition');}(new FormTemplate())->createVersion($slug,$definition,(int)($_SESSION['user']['id']??0),$summary);redirect('forms/templates/'.$slug.'/versions');}
 public function riskAssessment():void{$this->requireLogin();$clients=$this->assignedClients();$this->view('forms/privacy-risk-assessment',['title'=>'Privacy Risk Assessment','clients'=>$clients]);}
 public function ropa():void{$this->requireLogin();$client=$this->resolveClient();$id=(int)($_GET['id']??0);$ropa=[];$record=null;$template=null;if($id>0){$record=(new Ropa())->find($id);if(!$record){http_response_code(404);exit('ROPA record not found');}if((int)$record['client_id']!==(int)$client['id']||!$this->canAccessFormClient((int)$record['client_id'])){http_response_code(403);$this->view('errors/403',['title'=>'Access denied','message'=>'You do not have access to this ROPA record.']);exit;}$ropa=$record['data'];$ropa['id']=$record['id'];$ropa['client_id']=$record['client_id'];$ropa['process_name']=$record['process_name'];$ropa['status']=$record['status'];$templateForRecord=$record['form_definition'];if($templateForRecord){$template=['definition'=>$templateForRecord,'version_number'=>(int)($record['form_version_number']??1),'name'=>((string)($ropa['ropa_role']??'controller')==='processor'?'ROPA — Processor':'ROPA — Controller')];}else{$role=(string)($ropa['ropa_role']??'controller');$template=(new FormTemplate())->active($this->ropaSlug($role));}$_SESSION['ropa_edit_id']=$record['id'];}else{$role=strtolower((string)($_GET['role']??'controller'))==='processor'?'processor':'controller';$ropa['ropa_role']=$role;$template=(new FormTemplate())->active($this->ropaSlug($role));unset($_SESSION['ropa_edit_id']);}if(!$template){http_response_code(500);exit('ROPA form template is not configured');}$clients=$this->assignedClients();$records=(new Ropa())->forClient((int)$client['id']);$this->view('forms/ropa',compact('client','clients','records','record','ropa','template'));}
 public function ropaStore():void{$this->requireLogin();if(!Security::verifyCsrf($_POST['_csrf']??null)){http_response_code(419);exit('Invalid security token');}$client=$this->resolveClient();$id=(int)($_POST['id']??($_SESSION['ropa_edit_id']??0));$model=new Ropa();$record=$id>0?$model->find($id):null;if($id>0&&(!$record||!$this->canAccessFormClient((int)$record['client_id'])||(int)$record['client_id']!==(int)$client['id'])){http_response_code(403);exit('Access denied');}$role=$record?(strtolower((string)($record['data']['ropa_role']??'controller'))==='processor'?'processor':'controller'):(strtolower((string)($_POST['ropa_role']??'controller'))==='processor'?'processor':'controller');$template=$record&&$record['form_definition']?['definition'=>$record['form_definition']]:((new FormTemplate())->active($this->ropaSlug($role))?:null);if(!$template){http_response_code(500);exit('ROPA form template is not configured');}$definition=$template['definition']??[];$payload=$this->validateRopaPayload($definition,$_POST,$role,(int)$client['id']);$processName=trim((string)($payload['process_name']??''));if($processName===''){http_response_code(422);exit('Processing activity / process is required');}$data=['client_id'=>(int)$client['id'],'process_name'=>$processName,'status'=>trim((string)($payload['status']??'planned')),'payload'=>$payload,'created_by'=>(int)($_SESSION['user']['id']??0)];if($id>0){$data['id']=$id;$model->update($data);}else{$active=(new FormTemplate())->active($this->ropaSlug($role));if(!$active){http_response_code(500);exit('ROPA form template is not configured');}$data['form_version_id']=(int)$active['active_version_id'];$id=$model->create($data);}$_SESSION['ropa_edit_id']=$id;redirect('forms/ropa?client_id='.$client['id'].'&id='.$id);}
}
