<?php
namespace App\Controllers;
use App\Core\BaseController; use App\Core\Flash; use App\Core\Security; use App\Models\User; use App\Models\Client;
class UsersController extends BaseController
{
 private function ownedUser(int $id):?array{$u=(new User())->find($id);if(!$u)return null;if((int)($u['role_id']??0)===1&&!$this->isSuperuser()){http_response_code(403);$this->view('errors/403',['title'=>'Access denied','message'=>'Administrators cannot manage Superuser accounts.']);exit;}if($this->isSuperuser())return$u;if((int)($u['client_id']??0)!==$this->clientId()){http_response_code(403);$this->view('errors/403',['title'=>'Access denied','message'=>'You do not have access to this user account.']);exit;}return$u;}
 public function index(){ $this->requireLogin();$model=new User();$users=$this->isSuperuser()?$model->getAllUsers():$model->getAllUsers($this->clientId());$this->view('users/index',['title'=>'Users','users'=>$users]); }
 public function create(){ $this->requireLogin();$clients=$this->isSuperuser()?(new Client())->allClients():[];$this->view('users/create',['title'=>'Add User','clients'=>$clients]); }
 public function store(){ $this->requireLogin();$roleId=(int)($_POST['role_id']??3);if(!$this->isSuperuser()&&!in_array($roleId,[2,3],true))$roleId=3;$clientId=$this->isSuperuser()?(int)($_POST['client_id']??0):($this->clientId()??0);if($roleId!==1&&$clientId<=0){Flash::error('A client must be assigned to Admin and Client users.');redirect('users');return;}$model=new User();$model->create(['client_id'=>$roleId===1?null:$clientId,'fullname'=>trim($_POST['fullname']??''),'email'=>trim($_POST['email']??''),'password'=>password_hash($_POST['password']??'',PASSWORD_DEFAULT),'role_id'=>$roleId]);Flash::success('User created successfully.');redirect('users'); }
 public function edit(){ $this->requireLogin();if(!isset($_GET['id'])||!is_numeric($_GET['id']))redirect('users');$user=$this->ownedUser((int)$_GET['id']);if(!$user){Flash::error('User not found.');redirect('users');}$clients=$this->isSuperuser()?(new Client())->allClients():[];$this->view('users/edit',['title'=>'Edit User','user'=>$user,'clients'=>$clients]); }
 public function update(){ $this->requireLogin();$model=new User();$id=(int)$_POST['id'];$user=$this->ownedUser($id);if(!$user){Flash::error('User not found.');redirect('users');}$roleId=(int)$_POST['role_id'];if(!$this->isSuperuser()&&!in_array($roleId,[2,3],true))$roleId=(int)$user['role_id'];$clientId=$this->isSuperuser()?(int)($_POST['client_id']??0):(int)($user['client_id']??0);if($roleId!==1&&$clientId<=0){Flash::error('A client must be assigned to Admin and Client users.');redirect('users');return;}$model->update(['id'=>$id,'client_id'=>$roleId===1?null:$clientId,'fullname'=>trim($_POST['fullname']),'email'=>trim($_POST['email']),'role_id'=>$roleId,'status'=>(int)$_POST['status']]);Flash::success('User updated successfully.');redirect('users'); }
 public function delete(){ $this->requireLogin();if(!Security::verifyCsrf($_POST['_csrf']??null)){http_response_code(419);exit('Invalid security token');}if(!isset($_POST['id'])||!is_numeric($_POST['id']))redirect('users');$id=(int)$_POST['id'];if((int)$this->user()['id']===$id){Flash::error('You cannot delete your own account.');redirect('users');}$model=new User();$user=$this->ownedUser($id);if(!$user){Flash::error('User not found.');redirect('users');}if((int)$user['role_id']===1&&$model->countSuperusers()<=1){Flash::error('Cannot delete the last Superuser.');redirect('users');}$model->deleteUser($id);Flash::success('User deleted successfully.');redirect('users'); }
}
