<?php
namespace App\Models;
use App\Core\Model;
class ProcessingActivity extends Model
{
 public function forClient(int $clientId):array{$s=$this->db->prepare('SELECT * FROM processing_activities WHERE client_id=? ORDER BY updated_at DESC,id DESC');$s->execute([$clientId]);return$s->fetchAll();}
 public function find(int $id):?array{$s=$this->db->prepare('SELECT * FROM processing_activities WHERE id=? LIMIT 1');$s->execute([$id]);return$s->fetch()?:null;}
 public function create(array $d):int{$s=$this->db->prepare('INSERT INTO processing_activities(client_id,department,name,description,purpose,legal_basis,data_subjects,personal_data_categories,special_category_data,recipients,international_transfer,transfer_details,retention_period,security_measures,risk_level,status,owner_user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$d['client_id'],trim($d['department']??''),trim($d['name']),trim($d['description']??''),trim($d['purpose']??''),trim($d['legal_basis']??''),trim($d['data_subjects']??''),trim($d['personal_data_categories']??''),!empty($d['special_category_data'])?1:0,trim($d['recipients']??''),!empty($d['international_transfer'])?1:0,trim($d['transfer_details']??''),trim($d['retention_period']??''),trim($d['security_measures']??''),in_array($d['risk_level']??'', ['low','medium','high','critical'],true)?$d['risk_level']:'medium',in_array($d['status']??'', ['draft','active','under_review','archived'],true)?$d['status']:'draft',$d['owner_user_id']?:null]);return(int)$this->db->lastInsertId();}
 public function update(array $d):bool{$s=$this->db->prepare('UPDATE processing_activities SET department=?,name=?,description=?,purpose=?,legal_basis=?,data_subjects=?,personal_data_categories=?,special_category_data=?,recipients=?,international_transfer=?,transfer_details=?,retention_period=?,security_measures=?,risk_level=?,status=?,owner_user_id=? WHERE id=? AND client_id=?');return$s->execute([trim($d['department']??''),trim($d['name']),trim($d['description']??''),trim($d['purpose']??''),trim($d['legal_basis']??''),trim($d['data_subjects']??''),trim($d['personal_data_categories']??''),!empty($d['special_category_data'])?1:0,trim($d['recipients']??''),!empty($d['international_transfer'])?1:0,trim($d['transfer_details']??''),trim($d['retention_period']??''),trim($d['security_measures']??''),in_array($d['risk_level']??'', ['low','medium','high','critical'],true)?$d['risk_level']:'medium',in_array($d['status']??'', ['draft','active','under_review','archived'],true)?$d['status']:'draft',$d['owner_user_id']?:null,$d['id'],$d['client_id']]);}
 public function deleteForClient(int $id,int $clientId):bool{$s=$this->db->prepare('DELETE FROM processing_activities WHERE id=? AND client_id=?');return$s->execute([$id,$clientId]);}
}
